### ISSUE TITLE
PUT of a nonexistent ID inserts the record

### ISSUE THREAD

**Issue by fabriciofs** [viniciusbo/hapi-suricate#2]
If I make a PUT request (update) of a nonexistent ID, the record is inserted, and the correct one would be to return StatusCode 404

**Comment by viniciusbo** [comment]
That's beacuse of `{ upsert: true }` https://github.com/viniciusbo/hapi-suricate/blob/master/src/suricate.js#L45. I think that sould be removed as well. But that means every request should contain the whole record, not just the fields that should be updated (POST vs PUT).

**Comment by viniciusbo** [comment]
Fixed in version 1.1.0.
